name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Set package version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual trigger - using input version: ${{ github.event.inputs.version }}"
            npm version ${{ github.event.inputs.version }}
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "Release trigger - extracting version from tag"
            TAG_VERSION=${GITHUB_REF#refs/tags/v}
            echo "Tag version: $TAG_VERSION"
            # 버전 형식 검증
            if [[ $TAG_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              npm version $TAG_VERSION --no-git-tag-version
              echo "Version set to: $TAG_VERSION"
            else
              echo "Invalid version format: $TAG_VERSION"
              exit 1
            fi
          else
            echo "Unknown event type: ${{ github.event_name }}"
            exit 1
          fi

      - name: Build package
        run: npm run build

      - name: Publish to npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}